// One-off: replace mangled Vietnamese literals with their English
// equivalents in dashboard.js. Runs once via `node scripts/to-en-ui.mjs`.
// Idempotent: if the file is already English, the substring lookups
// still match (because we always look up the mangled-Vietnamese form).
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const targetPath = join(__dirname, '..', 'apps', 'extension', 'dashboard.js');

// Each mapping is built from a snippet we located in the file as
// either correct-Vietnamese text, mojibake (`?`-mangled or
// Latin-1-rendered) text. The matching is *substring-based* and
// intentionally tolerant: even if the file shows the text as
// `Sch` or `Kha h?c`, the search will still align as long as both
// sides agree on the exact mangled bytes.
const replacements = [
  // ===== SPACES_DATA =====
  ["icon: '??',", "icon: '🎨',"],
  ["name: 'C?M H?NG THI?T K?',", "name: 'DESIGN INSPIRATION',"],
  ["desc: '?nh ch?p m?n h?nh, b?ng m?u v? c?c m?u UI ???c thu th?p trong qu? tr?nh duy?t web.',",
   "desc: 'Screenshots, palette swatches and UI patterns captured while browsing the web.',"],
  ["['c?m h?ng', 'thi?t k?', 'design', 'inspiration', 'ui', 'ux', '?nh', 'image']",
   "['inspiration','design','inspiration','design','ui','ux','image','image']"],
  ["icon: '??',", "icon: '💻',"],
  ["name: 'GHI CH? C?NG NGH?',", "name: 'TECH NOTES',"],
  ["desc: 'C?c b?i b?o, ?o?n m? v? tin t?c c?ng ngh? t? qu? tr?nh duy?t web.',",
   "desc: 'Articles, snippets and tech news saved while reading online.',"],
  ["['c?ng ngh?', 'tech', 'code', 'css', 'frontend', 'backend', 'spatial', 'hci']",
   "['tech','tech','code','css','frontend','backend','spatial','hci']"],
  ["icon: '??',", "icon: '🗾',"],
  ["name: 'CHUY?N ?I NH?T B?N 2024',", "name: 'JAPAN TRIP 2024',"],
  ["desc: 'L?ch tr?nh bay, ??t ph?ng kh?ch s?n v? c?c ??a ?i?m d? ki?n tham quan.',",
   "desc: 'Flight itineraries, hotel bookings and places on the to-visit list.',"],
  ["['nh?t b?n', 'japan', 'trip', 'travel', 'chuy?n ?i', 'kh?ch s?n', 'l?ch tr?nh']",
   "['japan','japan','trip','travel','trip','hotel','itinerary']"],
  ["icon: '??',", "icon: '📚',"],
  ["name: 'T?I LI?U H?C T?P',", "name: 'STUDY MATERIALS',"],
  ["desc: 'C?c b?i b?o nghi?n c?u, n?i dung n?i b?t t? s?ch gi?o khoa v? ghi ch? h?c t?p.',",
   "desc: 'Research articles, highlights from textbooks and study notes.',"],
  ["['h?c t?p', 't?i li?u', 'research', 'nghi?n c?u', 'article', 'study', 'book']",
   "['study','materials','research','research','article','study','book']"],

  // ===== DEFAULT_REMINDERS =====
  ["title: 'Chu?n b? h?p: Ki?n tr?c h? th?ng',",
   "title: 'Prep meeting: System architecture',"],
  ["{ text: 'Xem l?i chi?n l??c b? nh? ??m cho ch? ?? ngo?i tuy?n', done: false },",
   "{ text: 'Review caching strategy for offline mode', done: false },"],
  ["{ text: 'Th?o lu?n v? WebSockets so v?i SSE', done: true },",
   "{ text: 'Discuss WebSockets vs SSE', done: true },"],
  ["{ text: 'Ki?m tra gi?i h?n t?n su?t API tr?n c?c endpoint m?i', done: false }",
   "{ text: 'Check API rate limits on the new endpoints', done: false }"],
  ["date: 'H?m qua',", "date: 'Yesterday',"],
  ["space: 'C?ng vi?c',", "space: 'Work',"],
  ["title: 'Todo list h?m nay',", "title: 'Today\\'s todo list',"],
  ["{ text: 'T?ng h?p t?i li?u ?? l?u trong tu?n', done: false },",
   "{ text: 'Review all items saved this week', done: false },"],
  ["{ text: 'G?n tags cho c?c note quan tr?ng', done: false },",
   "{ text: 'Tag important notes', done: false },"],
  ["{ text: 'Xem l?i 2 m?c c?n ?n t?p', done: true }",
   "{ text: 'Review 2 items that need revisiting', done: true }"],
  ["date: 'H?m nay',", "date: 'Today',"],
  ["space: 'H?c t?p',", "space: 'Study',"],

  // ===== auth =====
  ["payload.error && payload.error.message ? payload.error.message : 'Kh?ng th? x?c th?c.'",
   "payload.error && payload.error.message ? payload.error.message : 'Authentication failed.'"],
  ["setAuthError('signup-error', 'Vui l?ng nh?p ??y ?? th?ng tin.');",
   "setAuthError('signup-error', 'Please fill in all fields.');"],
  ["setAuthError('signup-error', 'Email ch?a ??ng ??nh d?ng.');",
   "setAuthError('signup-error', 'Email is not in a valid format.');"],
  ["setAuthError('signup-error', 'M?t kh?u c?n t?i thi?u 10 k? t?, g?m ch? hoa, ch? th??ng, s? v? k? t? ??c bi?t.');",
   "setAuthError('signup-error', 'Password must be at least 10 chars with upper/lower/digit/symbol.');"],
  ["setAuthError('signup-error', 'M?t kh?u nh?p l?i ch?a kh?p.');",
   "setAuthError('signup-error', 'Password confirmation does not match.');"],
  ["throw new Error('T?i kho?n ?? t?o. H?y x?c nh?n email r?i ??ng nh?p.');",
   "throw new Error('Account created — please confirm your email before signing in.');"],
  ["showToast('?? t?o t?i kho?n Mnemonics');",
   "showToast('Mnemonics account created');"],
  ["setAuthError('login-error', 'Vui l?ng nh?p email v? m?t kh?u.');",
   "setAuthError('login-error', 'Please enter email and password.');"],
  ["showToast('??ng nh?p th?nh c?ng');", "showToast('Signed in');"],
  ["showToast('?? ??ng xu?t');", "showToast('Signed out');"],
  ["showToast('T?i kho?n demo ?? b? t?t ? h?y ??ng k? ho?c ??ng nh?p.');",
   "showToast('Demo accounts are disabled — please sign up or sign in.');"],
  ["showToast('?? t? ??ng gia h?n phi?n');",
   "showToast('Session automatically renewed');"],
  ['// "B?t ??u mi?n ph?" while the avatar', '// "Get started for free" while the avatar'],

  // ===== comments =====
  ["// Ph?n lo?i m?t item v? nh?m ??nh d?ng chu?n ?? l?c/s?p x?p",
   "// Classify an item by format for filtering/sorting"],
  ['// "?nh" tab ? splitting them would force users to click two tabs to find',
   '// Image tab — splitting them would force users to click two tabs to find'],
  ["// L?y m?c th?i gian (ms) c?a item ?? l?c theo ng?y/th?ng/n?m",
   "// Get timestamp for an item so we can filter by day/month/year"],
  ["// Render cards c? ?p d?ng sort/filter + ? t?m ki?m hi?n t?i",
   "// Render cards with sort/filter and the current search query"],

  // ===== TOPIC_OPTIONS / BOOK_CATALOG =====
  ["{ id: 'marketing', label: 'Marketing', keywords: ['marketing','mkt','brand','th??ng hi?u','qu?ng c?o','ads','seo','content','kh?ch h?ng','s?n ph?m','product'] },",
   "{ id: 'marketing', label: 'Marketing', keywords: ['marketing','mkt','brand','brand','ads','ads','seo','content','customer','product','product'] },"],
  ["{ id: 'design', label: 'Thi?t k?', keywords: ['design','thi?t k?','ui','ux','inspiration','c?m h?ng','m?u','typography'] },",
   "{ id: 'design', label: 'Design', keywords: ['design','design','ui','ux','inspiration','inspiration','pattern','typography'] },"],
  ["{ id: 'tech', label: 'C?ng ngh?', keywords: ['tech','c?ng ngh?','code','css','frontend','backend','ai','spatial','hci'] },",
   "{ id: 'tech', label: 'Tech', keywords: ['tech','tech','code','css','frontend','backend','ai','spatial','hci'] },"],
  ["{ id: 'business', label: 'Kinh doanh', keywords: ['business','kinh doanh','startup','kh?i nghi?p','finance','t?i ch?nh','qu?n l?'] },",
   "{ id: 'business', label: 'Business', keywords: ['business','business','startup','startup','finance','finance','management'] },"],
  ["{ id: 'psychology', label: 'T?m l? h?c', keywords: ['psychology','t?m l?','habit','th?i quen','behavior','h?nh vi'] },",
   "{ id: 'psychology', label: 'Psychology', keywords: ['psychology','psychology','habit','habit','behavior','behavior'] },"],
  ["{ id: 'productivity', label: 'N?ng su?t', keywords: ['productivity','n?ng su?t','habit','ghi ch?','study','h?c t?p','focus'] },",
   "{ id: 'productivity', label: 'Productivity', keywords: ['productivity','productivity','habit','note','study','study','focus'] },"],
  ["{ id: 'language', label: 'Ngo?i ng?', keywords: ['english','ti?ng anh','language','ngo?i ng?','ielts','toeic'] },",
   "{ id: 'language', label: 'Language', keywords: ['english','english','language','language','ielts','toeic'] },"],
  ["{ id: 'writing', label: 'Vi?t l?ch', keywords: ['writing','vi?t','content','copywriting','storytelling'] }",
   "{ id: 'writing', label: 'Writing', keywords: ['writing','writing','content','copywriting','storytelling'] }"],

  // ===== BOOK_CATALOG (badge + emoji icons + titles in mangled form) =====
  ["'This Is Marketing', author: 'Seth Godin', badge: 'S?ch', color: '#5B3FE4', icon: '??'",
   "'This Is Marketing', author: 'Seth Godin', badge: 'Book', color: '#5B3FE4', icon: '📘'"],
  ["'Contagious: Why Things Catch On', author: 'Jonah Berger', badge: 'S?ch', color: '#e0447a', icon: '??'",
   "'Contagious: Why Things Catch On', author: 'Jonah Berger', badge: 'Book', color: '#e0447a', icon: '📕'"],
  ["title: 'Kh?a h?c Digital Marketing 4.0'",
   "title: 'Digital Marketing 4.0 course'"],
  ["title: 'Kh?i nghi?p tinh g?n'",
   "title: 'Lean startup'"],
  ["title: 'T?m l? h?c h?nh vi'",
   "title: 'Behavioral psychology'"],
  ["title: 'L?m ch? n?ng su?t c? nh?n'",
   "title: 'Master personal productivity'"],
  ["'The Design of Everyday Things', author: 'Don Norman', badge: 'S?ch', color: '#0ea5e9', icon: '??'",
   "'The Design of Everyday Things', author: 'Don Norman', badge: 'Book', color: '#0ea5e9', icon: '📘'"],
  ["'Refactoring UI', author: 'Wathan & Schoger', badge: 'S?ch', color: '#5B3FE4', icon: '??'",
   "'Refactoring UI', author: 'Wathan & Schoger', badge: 'Book', color: '#5B3FE4', icon: '📕'"],
  ["'UI/UX Design Foundations', author: 'Mnemonics Academy', badge: 'Kh?a h?c', color: '#10b981', icon: '??'",
   "'UI/UX Design Foundations', author: 'Mnemonics Academy', badge: 'Course', color: '#10b981', icon: '🎓'"],
  ["'Clean Code', author: 'Robert C. Martin', badge: 'S?ch', color: '#334155', icon: '??'",
   "'Clean Code', author: 'Robert C. Martin', badge: 'Book', color: '#334155', icon: '📘'"],
  ["'Pragmatic Programmer', author: 'Hunt & Thomas', badge: 'S?ch', color: '#f59e0b', icon: '??'",
   "'Pragmatic Programmer', author: 'Hunt & Thomas', badge: 'Book', color: '#f59e0b', icon: '📕'"],
  ["'Frontend Masters Path', author: 'Mnemonics Academy', badge: 'Kh?a h?c', color: '#5B3FE4', icon: '??'",
   "'Frontend Masters Path', author: 'Mnemonics Academy', badge: 'Course', color: '#5B3FE4', icon: '🎓'"],
  ["'The Lean Startup', author: 'Eric Ries', badge: 'S?ch', color: '#0ea5e9', icon: '??'",
   "'The Lean Startup', author: 'Eric Ries', badge: 'Book', color: '#0ea5e9', icon: '📘'"],
  ["'Zero to One', author: 'Peter Thiel', badge: 'S?ch', color: '#334155', icon: '??'",
   "'Zero to One', author: 'Peter Thiel', badge: 'Book', color: '#334155', icon: '📕'"],
  ["'Kh?i nghi?p tinh g?n', author: 'Mnemonics Academy', badge: 'Kh?a h?c', color: '#e0447a', icon: '??'",
   "'Lean startup', author: 'Mnemonics Academy', badge: 'Course', color: '#e0447a', icon: '🎓'"],
  ["'Thinking, Fast and Slow', author: 'Daniel Kahneman', badge: 'S?ch', color: '#5B3FE4', icon: '??'",
   "'Thinking, Fast and Slow', author: 'Daniel Kahneman', badge: 'Book', color: '#5B3FE4', icon: '📘'"],
  ["'Atomic Habits', author: 'James Clear', badge: 'S?ch', color: '#10b981', icon: '??'",
   "'Atomic Habits', author: 'James Clear', badge: 'Book', color: '#10b981', icon: '📕'"],
  ["'T?m l? h?c h?nh vi', author: 'Mnemonics Academy', badge: 'Kh?a h?c', color: '#f59e0b', icon: '??'",
   "'Behavioral psychology', author: 'Mnemonics Academy', badge: 'Course', color: '#f59e0b', icon: '🎓'"],
  ["'Deep Work', author: 'Cal Newport', badge: 'S?ch', color: '#334155', icon: '??'",
   "'Deep Work', author: 'Cal Newport', badge: 'Book', color: '#334155', icon: '📘'"],
  ["'L?m ch? n?ng su?t c? nh?n', author: 'Mnemonics Academy', badge: 'Kh?a h?c', color: '#5B3FE4', icon: '??'",
   "'Master personal productivity', author: 'Mnemonics Academy', badge: 'Course', color: '#5B3FE4', icon: '🎓'"],
  ["'English Grammar in Use', author: 'Raymond Murphy', badge: 'S?ch', color: '#0ea5e9', icon: '??'",
   "'English Grammar in Use', author: 'Raymond Murphy', badge: 'Book', color: '#0ea5e9', icon: '📘'"],
  ["'Word Power Made Easy', author: 'Norman Lewis', badge: 'S?ch', color: '#e0447a', icon: '??'",
   "'Word Power Made Easy', author: 'Norman Lewis', badge: 'Book', color: '#e0447a', icon: '📕'"],
  ["'IELTS 7.0+ Roadmap', author: 'Mnemonics Academy', badge: 'Kh?a h?c', color: '#10b981', icon: '??'",
   "'IELTS 7.0+ Roadmap', author: 'Mnemonics Academy', badge: 'Course', color: '#10b981', icon: '🎓'"],
  ["'On Writing Well', author: 'William Zinsser', badge: 'S?ch', color: '#f59e0b', icon: '??'",
   "'On Writing Well', author: 'William Zinsser', badge: 'Book', color: '#f59e0b', icon: '📘'"],
  ["'Everybody Writes', author: 'Ann Handley', badge: 'S?ch', color: '#5B3FE4', icon: '??'",
   "'Everybody Writes', author: 'Ann Handley', badge: 'Book', color: '#5B3FE4', icon: '📕'"],
  ["'Content & Copywriting', author: 'Mnemonics Academy', badge: 'Kh?a h?c', color: '#e0447a', icon: '??'",
   "'Content & Copywriting', author: 'Mnemonics Academy', badge: 'Course', color: '#e0447a', icon: '🎓'"],

  // ===== book panel UI =====
  ["<div class=\"book-panel-eyebrow\">? G?i ? cho b?n</div>",
   "<div class=\"book-panel-eyebrow\">✦ Suggested for you</div>"],
  ["<div class=\"book-panel-title\">S?ch & kh?a h?c n?i b?t</div>",
   "<div class=\"book-panel-title\">Featured books & courses</div>"],
  ['<div class="book-panel-topic">D?a tr?n l?nh v?c: <b>',
   '<div class="book-panel-topic">Based on interest: <b>'],
  ["<label>??i l?nh v?c</label>", "<label>Change topic</label>"],
  ['<div class="book-panel-foot">Mnemonics h?p t?c c?ng c?c nh? b?n s?ch & n?n t?ng kh?a h?c.<br>Ch?n l?nh v?c trong <b>C?i ??t</b> ?? c? nh?n h?a.</div>',
   '<div class="book-panel-foot">Mnemonics partners with bookshops & learning platforms.<br>Pick a topic in <b>Settings</b> to personalize.</div>'],

  // ===== detectTopicFromItems comment =====
  ["// ?o?n l?nh v?c quan t?m t? d? li?u ?? l?u n?u user ch?a ch?n th? c?ng",
   "// Infer topic of interest from saved items if user hasn't picked manually"],

  // ===== reminderToMemoryItem =====
  ["const kindLabel = reminder.kind === 'meeting' ? 'Bi?n b?n h?p' : 'Todo list';",
   "const kindLabel = reminder.kind === 'meeting' ? 'Meeting minutes' : 'Todo list';"],
  ["excerpt: `${kindLabel} ? ${doneCount}/${totalCount} ho?n th?nh`,",
   "excerpt: `${kindLabel} · ${doneCount}/${totalCount} done`,"],
  ["tags: ['nh?c nh?', reminder.kind === 'meeting' ? 'bi?n b?n h?p' : 'todo'],",
   "tags: ['reminder', reminder.kind === 'meeting' ? 'meeting' : 'todo'],"],
  ["date: reminder.date || 'H?m nay',", "date: reminder.date || 'Today',"],
  ["space: reminder.space || 'Nh?c nh?',", "space: reminder.space || 'Reminders',"],

  // ===== apiItemToLocalShape =====
  ["const title = item.title || (kind === 'link' ? 'Link ?? l?u' : 'M?c ?? l?u');",
   "const title = item.title || (kind === 'link' ? 'Saved link' : 'Saved item');"],

  // ===== resync + polling + item count comments =====
  ['until the user clicks "??ng b? l?n database" or the resync succeeds.',
   'until the user clicks "Sync to database" or the resync succeeds.'],
  ["// L?ng nghe khi extension popup l?u item m?i ? reload ngay",
   "// Listen for new items from the popup and reload"],
  ["// Fallback: poll m?i 3 gi?y ?? ch?c ch?n sync",
   "// Fallback: poll every 3 seconds to make sure we stay in sync"],
  ["if (el) el.textContent = items.length + ' k? ?c ?? ???c l?u trong th?ng n?y.';",
   "if (el) el.textContent = items.length + ' memories saved this month.';"],

  // ===== renderCards / card markup =====
  ["document.getElementById('item-count').textContent = `${data.length} k? ?c ?? ???c l?u trong th?ng n?y.`;",
   "document.getElementById('item-count').textContent = `${data.length} memories saved this month.`;"],
  ['// Build the "??ng b? l?n database" pill used by image/link/quote cards',
   '// Build the "Sync to database" pill used by image/link/quote cards'],
  ['title="Upload l?n Supabase">', 'title="Upload to Supabase">'],
  ['<span class="resync-dot"></span>??ng b? l?n database',
   '<span class="resync-dot"></span>Sync to database'],
  ['<h3>Kh?ng t?m th?y k?t qu?</h3>', '<h3>No results found</h3>'],
  ['<p>H?y th? t? kh?a kh?c ho?c th?m k? ?c m?i</p>',
   '<p>Try a different keyword or add a new memory</p>'],
  ["(item.tags && item.tags.includes('bi?n b?n h?p') ? 'BI?N B?N H?P' : 'TODO LIST')",
   "(item.tags && item.tags.includes('meeting') ? 'MEETING MINUTES' : 'TODO LIST')"],
  ["imageTitle = escapeHtml(item.title || (item.type === 'screenshot' ? '?nh ch?p m?n h?nh' : '?nh ?? l?u'));",
   "imageTitle = escapeHtml(item.title || (item.type === 'screenshot' ? 'Screenshot' : 'Saved image'));"],
  ['title="B?m ?? xem ?nh"', 'title="Click to view image"'],
  ["item.type === 'screenshot' ? 'Xem ?nh ch?p' : 'Xem ?nh'",
   "item.type === 'screenshot' ? 'View screenshot' : 'View image'"],
  ["${escapeHtml(item.title || 'Link ?? l?u')}",
   "${escapeHtml(item.title || 'Saved link')}"],
  ["${displayUrl || 'M? link'} ?</a>` : ''}",
   "${displayUrl || 'Open link'} ↗</a>` : ''}"],
  ["const fileName = escapeHtml(item.fileName || item.title || 'T?p ??nh k?m');",
   "const fileName = escapeHtml(item.fileName || item.title || 'Attachment');"],
  ["${escapeHtml(item.fileData)}`,\n          download=\"${fileName}\" data-file-download=\"1\" style=\"display:inline-flex;align-items:center;gap:6px;font-size:12px;font-weight:700;color:var(--purple);text-decoration:none;margin-top:8px\">? T?i v?</a>",
   "${escapeHtml(item.fileData)}`,\n          download=\"${fileName}\" data-file-download=\"1\" style=\"display:inline-flex;align-items:center;gap:6px;font-size:12px;font-weight:700;color:var(--purple);text-decoration:none;margin-top:8px\">↓ Download</a>"],
  ['flex-shrink:0\">??</div>', 'flex-shrink:0\">📎</div>'],
  ["${typeLabel} ? ${doneCount}/${totalCount} ho?n th?nh</div>`",
   "${typeLabel} · ${doneCount}/${totalCount} done</div>`"],
  ['title="B?m ?? tick / b? tick"', 'title="Click to tick / untick"'],
  ['>M? Nh?c nh?</button>', '>Open Reminders</button>'],
  ['>X?a</button>', '>Delete</button>'],
  ['>???</span>', '>⋮</span>'],
  ['>?? X?a</div>', '>✕ Delete</div>'],

  // ===== Spaces =====
  ['// "C?m h?ng" space shows both uploaded images AND cropped screenshots',
   '// Inspiration space shows both uploaded images AND cropped screenshots'],
  ['<h3>Ch?a c? kh?ng gian y?u th?ch</h3>', '<h3>No favorite spaces yet</h3>'],
  ['<p>B?m bi?u t??ng ng?i sao tr?n m?t kh?ng gian ?? ??a v?o m?c Y?u th?ch.</p>',
   '<p>Click the star icon on any space to put it in your Favorites.</p>'],
  ["title=\"${isFavorite ? 'B? y?u th?ch' : 'Th?m y?u th?ch'}\">?",
   "title=\"${isFavorite ? 'Remove favorite' : 'Add favorite'}\">★"],
  ['<span>${getSpaceCount(s)} m?c d? li?u ? ${relatedCount} m?c kh?p</span>',
   '<span>${getSpaceCount(s)} items · ${relatedCount} matches</span>'],
  ['<div class="space-open-hint">M? kh?ng gian ?</div>',
   '<div class="space-open-hint">Open space ›</div>'],
  ["showToast('?? b? kh?i Y?u th?ch');", "showToast('Removed from Favorites');"],
  ["showToast('?? th?m v?o Y?u th?ch');", "showToast('Added to Favorites');"],

  // ===== Space detail =====
  ['<button class="space-back-btn" id="space-detail-back">? Quay l?i</button>',
   '<button class="space-back-btn" id="space-detail-back">← Back</button>'],
  ["${isFavorite ? '? ?? y?u th?ch' : '? Y?u th?ch'}",
   "${isFavorite ? '★ Favorited' : '☆ Favorite'}"],
  ['<button class="space-detail-btn" id="space-detail-open-dashboard">Xem trong l?u tr?</button>',
   '<button class="space-detail-btn" id="space-detail-open-dashboard">Open in dashboard</button>'],
  ['<span>${getSpaceCount(space)} m?c d? li?u</span>',
   '<span>${getSpaceCount(space)} items</span>'],
  ['<span>${getSpaceItems(space).length} m?c ?ang kh?p v?i d? li?u demo/l?u th?t</span>',
   '<span>${getSpaceItems(space).length} items matching your saved data</span>'],
  ['<span>C?p nh?t g?n ??y</span>', '<span>Recently updated</span>'],
  ['placeholder="T?m trong kh?ng gian n?y..."',
   'placeholder="Search inside this space..."'],
  ['<h3>Ch?a c? m?c n?o trong kh?ng gian n?y</h3>',
   '<h3>No items in this space yet</h3>'],
  ['<p>L?u th?m ?nh, b?i vi?t ho?c ghi ch? c? tag li?n quan ?? ch?ng t? hi?n ? ??y.</p>',
   '<p>Save images, articles or notes with related tags and they will show up here.</p>'],
  ["{ article:'B?i vi?t', image:'?nh', note:'Ghi ch?', quote:'Tr?ch d?n', code:'M? ngu?n' }",
   "{ article:'Article', image:'Image', note:'Note', quote:'Quote', code:'Code' }"],
  ["const title = item.title || item.quote || item.note || 'K? ?c ?? l?u';",
   "const title = item.title || item.quote || item.note || 'Saved memory';"],
  ["(item.checks || []).map(function(c) { return c.text; }).join(' ? ')",
   "(item.checks || []).map(function(c) { return c.text; }).join(' · ')"],
  ['<button class="space-item-open" data-space-open-url="${escapeHtml(url)}">M? ngu?n</button>',
   '<button class="space-item-open" data-space-open-url="${escapeHtml(url)}">Open source</button>'],

  // ===== Reminders =====
  ["${getFilteredReminders().length} m?c nh?c nh?",
   "${getFilteredReminders().length} reminders"],
  ["'<h3>Ch?a c? nh?c nh? ph? h?p</h3><p>T?o checklist m?i ho?c ??i b? l?c kh?c.</p>'",
   "'<h3>No matching reminders</h3><p>Create a new checklist or change the filter.</p>'"],
  ["item.kind === 'meeting' ? 'BI?N B?N H?P' : 'TODO LIST'",
   "item.kind === 'meeting' ? 'MEETING MINUTES' : 'TODO LIST'"],
  ["${doneCount}/${totalCount} ho?n th?nh",
   "${doneCount}/${totalCount} done"],
  ["${escapeHtml(item.date || 'H?m nay')}",
   "${escapeHtml(item.date || 'Today')}"],
  ['<span style="color:#ddd;margin:0 6px">?</span>', '<span style="color:#ddd;margin:0 6px">·</span>'],
  ["${escapeHtml(item.space || 'C?ng vi?c')}",
   "${escapeHtml(item.space || 'Work')}"],
  ['<button class="reminder-delete" data-reminder-delete="${escapeHtml(safeId)}">X?a</button>',
   '<button class="reminder-delete" data-reminder-delete="${escapeHtml(safeId)}">Delete</button>'],
  ["const space = spaceEl ? spaceEl.value.trim() : 'C?ng vi?c';",
   "const space = spaceEl ? spaceEl.value.trim() : 'Work';"],
  ["showToast('Nh?p ti?u ?? v? ?t nh?t 1 checklist nh?!');",
   "showToast('Enter a title and at least 1 checklist item!');"],
  ["date: 'V?a xong',", "date: 'Just now',"],
  ["space: space || 'C?ng vi?c',", "space: space || 'Work',"],
  ["if (spaceEl) spaceEl.value = space || 'C?ng vi?c';",
   "if (spaceEl) spaceEl.value = space || 'Work';"],
  ["showToast('? ?? l?u nh?c nh?');", "showToast('✓ Reminder saved');"],
  ["showToast('?? ?? x?a nh?c nh?');", "showToast('Reminder deleted');"],

  // ===== Search =====
  ['// K?t h?p search v?i sort/filter hi?n t?i', '// Combine search with current sort/filter'],
  ['// T?m ki?m th? c?ng, kh?ng c?n AI', '// Manual search without AI'],
  ["`T?m th?y <b>${matched.length}</b> k?t qu? li?n quan ??n \"<b>${query}</b>\". C?c m?c li?n quan nh?t hi?n th? b?n d??i.`",
   "`Found <b>${matched.length}</b> results for \"<b>${query}</b>\". The closest matches are shown below.`"],
  ["`Kh?ng t?m th?y k?t qu? n?o cho \"<b>${query}</b>\". Th? t? kh?a kh?c nh?!`",
   "`No results for \"<b>${query}</b>\". Try a different keyword!`"],

  // ===== Image viewer =====
  ["titleEl.textContent = title || '?nh ?? l?u'",
   "titleEl.textContent = title || 'Saved image'"],
  ["title: title || '?nh g?c'", "title: title || 'Original image'"],
  ["showToast('Kh?ng th? m? ?nh g?c');", "showToast('Could not open original image');"],

  // ===== Modal =====
  ["let modalFileData = null;    // base64 c?a file/?nh ?? ch?n ho?c d?n",
   "let modalFileData = null;    // base64 of a file/image to paste or attach"],
  ["Nh?p n?i dung ?? AI t?o tags...",
   "Enter some content and AI will suggest tags..."],
  ["// Hi?n/?n ? URL v? ? file t?y theo lo?i ?? ch?n",
   "// Show/hide URL and file inputs based on the selected type"],
  ["D?n ?nh ch?p m?n h?nh (Ctrl/Cmd+V) v?o ??y, ho?c ch?n t?p ?nh",
   "Paste a screenshot (Ctrl/Cmd+V) here, or pick an image file"],
  ["Ch?n ?nh t? m?y", "Pick an image from your device"],
  ["Ch?n t?p ??nh k?m", "Pick an attachment"],
  ["// Gi?i h?n ~4MB ?? v?a quota storage",
   "// Cap at ~4MB so we stay within the storage quota"],
  ["showToast('T?p qu? l?n (t?i ?a 4MB cho b?n l?u offline)');",
   "showToast('File too large (max 4MB for offline items)');"],
  ["modalFileName = file.name || 't?p-??nh-k?m';",
   "modalFileName = file.name || 'attachment';"],
  ["<div style=\"font-size:12px;color:var(--gray-text)\">?? ' + escapeHtml(modalFileName) + ' ? ' + modalFileSize + '</div>';",
   "<div style=\"font-size:12px;color:var(--gray-text)\">📄 ' + escapeHtml(modalFileName) + ' · ' + modalFileSize + '</div>';"],
  ["// Cho ph?p d?n ?nh ch?p m?n h?nh tr?c ti?p v?o modal",
   "// Allow pasting screenshots directly into the modal"],
  ["showToast('?? ?? d?n ?nh ch?p m?n h?nh');",
   "showToast('Screenshot pasted');"],

  // ===== Inline stopwords list =====
  ["const stopwords = ['the','a','an','of','in','on','for','to','and','or','is','are','c?','c?a','v?','v?i','t?','n?y','??','cho','m?t','c?c','???c','kh?ng','th?'];",
   "const stopwords = ['the','a','an','of','in','on','for','to','and','or','is','are','the','of','and','with','of','this','or','for','one','the','be','not','and'];"],
  ["'c?','c?a','v?','v?i','t?','n?y','??','cho','m?t','c?c','???c','kh?ng']",
   "'the','of','and','with','of','this','or','for','one','the','be','not'"],

  // ===== Form validate =====
  ["// Ki?m tra d? li?u t?i thi?u theo t?ng lo?i",
   "// Check minimum data for each capture type"],
  ["showToast('Nh?p ???ng d?n (URL) nh?!');",
   "showToast('Enter a URL!');"],
  ["showToast('H?y ch?n/d?n t?p ho?c ?nh nh?!');",
   "showToast('Please pick or paste a file or image!');"],
  ["showToast('Vui l?ng nh?p n?i dung!');",
   "showToast('Please enter some content!');"],
  ["date: 'V?a xong', space: 'M?i l?u',",
   "date: 'Just now', space: 'Just saved',"],
  ["newItem.title = title || (link.replace(/^https?:\\/\\//, '').slice(0, 60)) || 'Link ?? l?u';",
   "newItem.title = title || (link.replace(/^https?:\\/\\//, '').slice(0, 60)) || 'Saved link';"],
  ["newItem.title = title || (type === 'screenshot' ? '?nh ch?p m?n h?nh' : '?nh ?? l?u');",
   "newItem.title = title || (type === 'screenshot' ? 'Screenshot' : 'Saved image');"],
  ["newItem.tags = type === 'screenshot' ? ['?nh ch?p'] : ['?nh'];",
   "newItem.tags = type === 'screenshot' ? ['screenshot'] : ['image'];"],
  ["newItem.tags = ['t?p'];", "newItem.tags = ['file'];"],
  ["showToast('? ?? l?u k? ?c th?nh c?ng!');",
   "showToast('✓ Memory saved successfully!');"],
  ["showToast('L?i khi l?u: ' + err.message);",
   "showToast('Save failed: ' + err.message);"],

  // ===== Theme + settings =====
  ["// T? ??i theo h? th?ng khi ?ang ? ch? ?? 'system'",
   "// Auto-switch with system when in 'system' mode"],
  ["// ??ng b? giao di?n trang C?i ??t v?i state",
   "// Sync settings page UI with current state"],
  ["(currentUser.name || currentUser.email) : 'Kh?ch'",
   "(currentUser.name || currentUser.email) : 'Guest'"],
  ["loggedIn ? currentUser.email : 'Ch?a ??ng nh?p'",
   "loggedIn ? currentUser.email : 'Not signed in'"],
  ["loggedIn ? '??ng xu?t' : '??ng nh?p'",
   "loggedIn ? 'Sign out' : 'Sign in'"],
  ["((currentUser.plan || 'Memory') + ' (mi?n ph?)')",
   "((currentUser.plan || 'Memory') + ' (free)')"],
  ["'Memory (mi?n ph?)'", "'Memory (free)'"],
  ["showToast('? ?? xu?t d? li?u th?nh c?ng');",
   "showToast('✓ Export complete');"],
  ["showToast('T?p kh?ng h?p l?!');",
   "showToast('Invalid file!');"],
  ["showToast('? ?? nh?p ' + newItems.length + ' m?c th?nh c?ng');",
   "showToast('✓ Imported ' + newItems.length + ' items');"],
  ["showToast('L?i ??c t?p: ' + err.message);",
   "showToast('Failed to read file: ' + err.message);"],
  ["X?a TO?N B? k? ?c v? nh?c nh?? H?nh ??ng n?y kh?ng th? ho?n t?c.\\n\\nG?i ?: h?y Xu?t d? li?u tr??c ?? sao l?u.",
   "Delete ALL memories and reminders? This cannot be undone.\\n\\nTip: Export your data first as a backup."],
  ["showToast('?? ?? x?a to?n b? d? li?u');",
   "showToast('All data has been deleted');"],

  // ===== Book/open misc toasts =====
  ["showToast('?? ' + bookCard.dataset.bookOpen + ' ? m? trang ??i t?c (demo)');",
   "showToast('Opening ' + bookCard.dataset.bookOpen + ' on the partner page (demo)');"],
  ["// ---- Modal: ??i lo?i ? hi?n ? URL / file ----",
   "// ---- Modal: change type → show URL/file input ----"],
  ["showToast('?? Chuy?n h??ng ??n thanh to?n...');",
   "showToast('Redirecting to checkout…');"],

  // ===== Misc =====
  ["// \"??ng b? l?n database\" ? re-run the upload pipeline for an item that",
   "// Clicking Sync to database — re-run upload pipeline for an item that"],
  ["// Click ra ngo?i ? ??ng dropdown", "// Click outside to close dropdown"],
  ["// Event delegation cho to?n b? cards container",
   "// Event delegation for the cards container"],
  ["// B?m v?o ???", "// Click on a card"],
  ["// B?m v?o X?a", "// Click delete"],
  ["// B?m m? link", "// Click to open link"],
  ["showToast('?? ?? x?a k? ?c');", "showToast('Memory deleted');"],
  ["Trang n?y c?n ch?y trong extension context ?? x?a tr?n server.",
   "This page must run inside the extension to delete from the server."],
  ["reject(new Error(chrome.runtime.lastError.message || 'Kh?ng g?i ???c background script.'));",
   "reject(new Error(chrome.runtime.lastError.message || 'Could not reach the background script.'));"],
  ["else reject(new Error((response && response.error) || 'API x?a th?t b?i.'));",
   "else reject(new Error((response && response.error) || 'Delete API failed.'));"],
  ["showToast('Kh?ng t?m th?y trong dashboard ?? ??ng b?.');",
   "showToast('Not found in the dashboard to sync.');"],
  ["btn.innerHTML = '<span class=\"resync-dot\"></span>?ang upload...';",
   "btn.innerHTML = '<span class=\"resync-dot\"></span>Uploading...';"],
  ["Trang n?y c?n ch?y trong extension context ?? ??ng b?.",
   "This page must run inside the extension to sync."],
  ["showToast('Kh?ng ??ng b? ???c: ' + chrome.runtime.lastError.message);",
   "showToast('Sync failed: ' + chrome.runtime.lastError.message);"],
  ["showToast('? ?? upload l?n Supabase');",
   "showToast('✓ Uploaded to Supabase');"],
  ["showToast('Kh?ng ??ng b? ???c: ' + msg);",
   "showToast('Sync failed: ' + msg);"],
];

let src = await readFile(targetPath, 'utf8');
let applied = 0;
const failures = [];
for (const [bad, good] of replacements) {
  if (!src.includes(bad)) {
    failures.push(bad);
    continue;
  }
  src = src.split(bad).join(good);
  applied++;
}
await writeFile(targetPath, src, 'utf8');
console.log(`Applied: ${applied}`);
if (failures.length) {
  console.log(`Not matched (${failures.length}):`);
  for (const f of failures.slice(0, 30)) console.log(' - ' + JSON.stringify(f.slice(0, 90)));
}
