import { config } from 'dotenv';
import { resolve } from 'path';
import { createPool } from '@mnemonics/database';
config({ path: resolve(process.cwd(), '.env') });
config({ path: resolve(process.cwd(), '../../.env') });
const pool = createPool(process.env.DATABASE_URL || '');
const r = await pool.query("SELECT id, type, status, attempts, max_attempts, item_id, created_at FROM jobs WHERE status = 'pending'");
console.log('---pending jobs---');
r.rows.forEach(row => console.log(`  ${row.id.slice(0,8)} ${row.type.padEnd(6)} ${row.status.padEnd(10)} att=${row.attempts}/${row.max_attempts} item=${row.item_id.slice(0,8)} created=${row.created_at.toISOString()}`));
console.log('Total pending:', r.rowCount);
const proc = await pool.query("SELECT id, type, status, attempts, max_attempts, item_id, updated_at FROM jobs WHERE status = 'processing'");
console.log('---processing jobs---');
proc.rows.forEach(row => console.log(`  ${row.id.slice(0,8)} ${row.type.padEnd(6)} ${row.status.padEnd(10)} att=${row.attempts}/${row.max_attempts} item=${row.item_id.slice(0,8)} updated=${row.updated_at.toISOString()}`));
console.log('Total processing:', proc.rowCount);
await pool.end();